displayName=Ground Item Sounds
author=Pharros, NathanVegetable
support=https://github.com/ThePharros/ground-item-sounds
description=Plays sounds for ground items based on your Ground Items settings.
tags=ground item,sound,notification,drop,loot
plugins=com.grounditemsounds.GroundItemSoundsPlugin