displayName=Ground Item Sounds
author=Pharros, NathanVegetable
description=Plays sounds for ground items based on your Ground Items settings.
tags=ground item,sound,notification,drop,loot
plugins=com.grounditemsounds.GroundItemSoundsPlugin
build=standard
version=1.2
